### ISSUE TITLE
Update demo schedule link on website

### ISSUE THREAD

**Issue by bspircuquickadmit** [quickadmit/quickadmit.github.io#1]
I need to update the link people go to when they select to schedule a demo from the website. I've created a new link that rounds robin between David and I with a lot more availability and east coast hours. here's the new link:

https://meetings.hubspot.com/bspircu/demo-call-round-robin

![Screen Shot 2024-09-10 at 10 50 47 AM](https://github.com/user-attachments/assets/fc2f34f6-10de-41bd-b25d-b75cf10bda22)

**Comment by adamrt** [comment]
@abuelgheit This website is in the https://github.com/quickadmit/quickadmit.github.io repository. The website is hosted on github. The instructions to build and deploy are in the readme. Let me know if you have any questions about it. Thanks!

**Comment by abuelgheit** [comment]
Deployed!
